version: '3.8'

services:
  vue-service:
    container_name: vue-container
    build: ./vue-container
    ports:
      - 8080:8080
    # systemctl を有効にするもの。
    privileged: true
    # tty, stdin_open しておくと exec するときに -it がいらないみたい。
    tty: true
    stdin_open: true
    command: /bin/sh
    volumes:
      - ./app/flower-stuff-easy-web-vue:/app

  django-service:
    container_name: django-container
    build: ./django-container
    ports:
      - 8000:8000
    # systemctl を有効にするもの。
    privileged: true
    # tty, stdin_open しておくと exec するときに -it がいらないみたい。
    tty: true
    stdin_open: true
    command: /bin/sh
    volumes:
      - ./app/flower-stuff-easy-web-django:/app
    environment:
      - APP_HDF5_DRIVE_ID=10PjbaGKUoNs1a0vPkAZ5z4Inl-ioaW6c
      - APP_HDF5_VERSION=2.0.0
      - APP_PINCODE=1234
      - DJANGO_SECRET_KEY=django-insecure-xxxxx
      - DISABLE_COLLECTSTATIC=1
